# Generated by Django 6.0.4 on 2026-05-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_examtype_alter_task_options_alter_taskstep_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_image',
        ),
        migrations.RemoveField(
            model_name='taskstep',
            name='image',
        ),
        migrations.AddField(
            model_name='task',
            name='task_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='taskstep',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
