# Generated by Django 6.0.4 on 2026-04-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_profile_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('oge', 'ОГЭ'), ('ege', 'ЕГЭ')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
