# Generated by Django 6.0.4 on 2026-04-25 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_exam_type_user_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
