# Generated by Django 6.0.4 on 2026-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_teacher_user_teacher_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('EGE', 'ЕГЭ'), ('OGE', 'ОГЭ')], max_length=10),
        ),
    ]
