# Generated by Django 6.0.4 on 2026-05-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Для учителей: пока не подтверждён администратором — не может войти.', verbose_name='Аккаунт подтверждён'),
        ),
        migrations.AlterField(
            model_name='user',
            name='exam_type',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
