# Generated by Django 6.0.4 on 2026-05-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_task_image_remove_taskstep_image_and_more'),
        ('users', '0006_user_is_approved_alter_user_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subject_links',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='tasks.subject', verbose_name='Предметы (из БД)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
